version: '3.8'

services:
  falkordb:
    image: falkordb/falkordb:latest
    container_name: ai-agent-falkordb
    ports:
      - "6379:6379"
      - "3000:3000"
    volumes:
      - falkordb_data:/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: ai-agent-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - FALKORDB_HOST=falkordb
      - FALKORDB_PORT=6379
    env_file:
      - ./backend/.env
    depends_on:
      - falkordb
    restart: unless-stopped

  frontend:
    image: node:18-alpine
    container_name: ai-agent-frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  falkordb_data:
